[package]
name = "linfa_test"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
linfa = "0.7.0"
linfa-trees = "0.7.0"
ndarray = { version = "0.15.6", default-features = false }
ndarray-csv = "0.5.2"
