[package]
name = "cli_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive"] }
colored = "2.1.0"
env_logger = "0.11.5"
indicatif = "0.17.8"
log = "0.4.22"
